### ISSUE TITLE
number of categories

### ISSUE THREAD

**Issue by un-lock-me** [askerlee/vmfmix#3]
may please let me know about the number of categories in your implementation,
if you considered all the categories in the 20news? why there isnt any K in the implementation?
how you detect a topic is related in which category in testing part?

Many thanks :)

**Comment by askerlee** [comment]
If memory serves, 20news contains 20 categories, and Reuters contains 10 categories. There are no direct mapping between these categories and derived topics. But a rule of thumb is, if you have more categories, that means more diverse semantics, and thus you need larger K.

In the test part, I didn't compute the proportions of each topic in each category. Instead I let svm find their relationship automatically. Of course you could easily compute an average topic proportion for each category, by averaging the topic proportions of all documents in this category.

**Comment by un-lock-me** [comment]
So May I ask you to correct the sentence below if that is wrong,

I was supposed to use svm or NB after topic modeling to evaluate my model, by that in testing part if a new bunch of documents have given to the SVM model it can assign a topic to those documents.
if the belonging to a category does not matter in the testing part, what does 69% means?
it means the topic driven of documents in testin part just belong to one of the categories in training model?

**Comment by saria85** [comment]
Also may please tell that which part of https://github.com/askerlee/topicvec/blob/master/topicExp.py
TopicExp I have to use,
It seems it has dependencies to other part of the TopicVec project.

Thanks:)

**Comment by askerlee** [comment]
Please search for SVMBOW. It has the simplest processing and does not involve topics.

**Comment by un-lock-me** [comment]
Many thanks:)

**Comment by askerlee** [comment]
The topic proportions are features of each document. The classifier (svm or nb) uses these features to decide a document belongs to which category.

To put it figuratively, a document is like a person. The topic proportions are the topics he usually reads. The categories are which party he belongs to: Republican or Democrat? There is no one to one mapping of the reading topics to his political inclination. But you could make a fairly reliable guess from the books he reads.

**Comment by saria85** [comment]
the example was so goood,
appreciate your time:)

**Comment by saria85** [comment]
I have a question,
I am so sorry for asking many questions:(

I really do not know how to search my question to get the result,
(one explanation I can not use BOW SVM, cause I have to implement LDA SVM)

I searched a lot,
for me the process has to be like this
https://stats.stackexchange.com/questions/138352/is-this-a-correct-way-to-do-document-classification-using-topic-modeling

or like this paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3886981/

MY QUESTION:
you said that I should use this format : label,featureindex:featurevalue to
send this vector to classifier,
my question is that if the feature vector of some terms vary in terms of
their method?
for example BOW, TFIDF, LDA, bow the feature vector is the frequency of the
words in document, TFIDF is times of frequency and the weight, LDA is the
probability?

Am I correct?

I do not know if I am making that hard, or just missing some simple thing
for example in your file you have this   6 44:1 94:1 254:1 329:1 it means
label=6  feature index=44  and feature value=1   but for ma feature value
should be a probability



I know that my questions is a lot,
if you had time i would appreciate if you could clarify me on this,

Many thanks,
saria
